version: '3.8'

services:
  # Redis service for event analytics
  redis:
    image: redis:7-alpine
    container_name: event-analytics-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - event-analytics-network

  # FastAPI application
  event-analytics-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: event-analytics-api
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - PYTHONPATH=/app
    volumes:
      - ./persistent_events:/app/persistent_events
      - ./backups:/app/backups
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - event-analytics-network
    restart: unless-stopped

volumes:
  redis_data:
    driver: local

networks:
  event-analytics-network:
    driver: bridge 